services:
  api-franken:
    container_name: api-franken
    build:
      context: .
      dockerfile: ./utils/recipes/Dockerfile_app
    volumes:
      - ./api:/app
    ports:
      - "8002:80"
    environment:
      - SERVER_NAME=:80
#  api-apache2:
#    container_name: api-apache2
#    build:
#      context: .
#      dockerfile: ./utils/recipes/Dockerfile_apache2
#    volumes:
#      - ./api:/var/www
#      - ./utils/recipes/conf:/etc/apache2/sites-enabled
#    ports:
#      - "8002:80"
#    environment:
#      - SERVER_NAME=:80